global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "rules.yml"

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
      - targets: ["192.168.122.172:9090"] # rhel target
