global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - 'localhost:9090'
        - '192.168.122.172:9090'
      
  - job_name: 'blackbox_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9115'

  - job_name: "node_exporter"
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9100'
        - '192.168.122.172:9100'
